export const provincias_aqp =[
    { provinciaId:"Arequipa", provinciaName:"Arequipa"},
    { provinciaId:"Camana", provinciaName:"Camaná"},
    { provinciaId:"Caraveli", provinciaName:"Caravelí"},
    { provinciaId:"Castilla", provinciaName:"Castilla"},
    { provinciaId:"Caylloma", provinciaName:"Caylloma"},
    { provinciaId:"Condesuyos", provinciaName:"Condesuyos"},
    { provinciaId:"Islay", provinciaName:"Islay"},
    { provinciaId:"La Union", provinciaName:"La Unión"}
];
export const distritos_aqp = {
    "":[],
    "Arequipa":[
        {distritoId:"Alto Selva Alegre", distritoName:"Alto Selva Alegre"},
        {distritoId:"Cercado", distritoName:"Arequipa(Cercado)"},
        {distritoId:"Cayma", distritoName:"Cayma"},
        {distritoId:"Cerro Colorado", distritoName:"Cerro Colorado"},
        {distritoId:"Characato", distritoName:"Characato"},
        {distritoId:"Chiguata", distritoName:"Chiguata"},
        {distritoId:"Jacobo Hunter", distritoName:"Jacobo Hunter"},
        {distritoId:"Jose Luis Bustamante y Rivero", distritoName:"José Luis Bustamante y Rivero"},
        {distritoId:"La Joya", distritoName:"La Joya"},
        {distritoId:"Mariano Melgar", distritoName:"Mariano Melgar"},
        {distritoId:"Miraflores", distritoName:"Miraflores"},
        {distritoId:"Mollebaya", distritoName:"Mollebaya"},
        {distritoId:"Paucarpata", distritoName:"Paucarpata"},
        {distritoId:"Pocsi", distritoName:"Pocsi"},
        {distritoId:"Polobaya", distritoName:"Polobaya"},
        {distritoId:"Quequenha", distritoName:"Quequeña"},
        {distritoId:"Sabandia", distritoName:"Sabandía"},
        {distritoId:"Sachaca", distritoName:"Sachaca"},
        {distritoId:"San Juan de Siguas", distritoName:"San Juan de Siguas"},
        {distritoId:"San Juan de Tarucani", distritoName:"San Juan de Tarucani"},
        {distritoId:"Santa Isabel de Siguas", distritoName:"Santa Isabel de Siguas"},
        {distritoId:"Santa Rita de Siguas", distritoName:"Santa Rita de Siguas"},
        {distritoId:"Socabaya", distritoName:"Socabaya"},
        {distritoId:"Tiabaya", distritoName:"Tiabaya"},
        {distritoId:"Uchumayo", distritoName:"Uchumayo"},
        {distritoId:"Vitor", distritoName:"Vítor"},
        {distritoId:"Yanahuara", distritoName:"Yanahuara"},
        {distritoId:"Yarabamba", distritoName:"Yarabamba"},
        {distritoId:"Yura", distritoName:"Yura"}
    ],
    "Camana":[
        {distritoId:"Camana", distritoName:"Camaná"},
        {distritoId:"Jose Maria Quimper", distritoName:"José María Quimper"},
        {distritoId:"Mariano Nicolas Valcarcel", distritoName:"Mariano Nicolás Valcárcel"},
        {distritoId:"Mariscal Caceres", distritoName:"Mariscal Cáceres"},
        {distritoId:"Nicolas de Pierola", distritoName:"Nicolás de Piérola"},
        {distritoId:"Oconha", distritoName:"Ocoña"},
        {distritoId:"Quilca", distritoName:"Quilca"},
        {distritoId:"Samuel Pastor", distritoName:"Samuel Pastor"}
    ],
    "Caraveli":[
        {distritoId:"Acari", distritoName:"Acarí"},
        {distritoId:"Atico", distritoName:"Atico"},
        {distritoId:"Atiquipa", distritoName:"Atiquipa"},
        {distritoId:"Bella Union", distritoName:"Bella Unión"},
        {distritoId:"Cahuacho", distritoName:"Cahuacho"},
        {distritoId:"Caraveli", distritoName:"Caravelí"},
        {distritoId:"Chala", distritoName:"Chala"},
        {distritoId:"Chaparra", distritoName:"Chaparra"},
        {distritoId:"Huanuhuanu", distritoName:"Huanuhuanu"},
        {distritoId:"Jaqui", distritoName:"Jaqui"},
        {distritoId:"Lomas", distritoName:"Lomas"},
        {distritoId:"Quicacha", distritoName:"Quicacha"},
        {distritoId:"Yauca", distritoName:"Yauca"},
    ],
    "Castilla":[
        {distritoId:"Andahua", distritoName:"Andahua"},
        {distritoId:"Aplao", distritoName:"Aplao"},
        {distritoId:"Ayo", distritoName:"Ayo"},
        {distritoId:"Chachas", distritoName:"Chachas"},
        {distritoId:"Chilcaymarca", distritoName:"Chilcaymarca"},
        {distritoId:"Choco", distritoName:"Choco"},
        {distritoId:"Huancarqui", distritoName:"Huancarqui"},
        {distritoId:"Machaguay", distritoName:"Machaguay"},
        {distritoId:"Orcopampa", distritoName:"Orcopampa"},
        {distritoId:"Pampacolca", distritoName:"Pampacolca"},
        {distritoId:"Tipan", distritoName:"Tipán"},
        {distritoId:"Unhon", distritoName:"Uñón"},
        {distritoId:"Uraca", distritoName:"Uraca"},
        {distritoId:"Viraco", distritoName:"Viraco"}        
    ],
    "Caylloma":[
        {distritoId:"Achoma", distritoName:"Achoma"},
        {distritoId:"Cabanaconde", distritoName:"Cabanaconde"},
        {distritoId:"Callalli", distritoName:"Callalli"},
        {distritoId:"Caylloma", distritoName:"Caylloma"},
        {distritoId:"Chivay", distritoName:"Chivay"},
        {distritoId:"Coporaque", distritoName:"Coporaque"},
        {distritoId:"Huambo", distritoName:"Huambo"},
        {distritoId:"Huanca", distritoName:"Huanca"},
        {distritoId:"Ichupampa", distritoName:"Ichupampa"},
        {distritoId:"Lari", distritoName:"Lari"},
        {distritoId:"Lluta", distritoName:"Lluta"},
        {distritoId:"Maca", distritoName:"Maca"},
        {distritoId:"Madrigal", distritoName:"Madrigal"},
        {distritoId:"Majes", distritoName:"Majes"},
        {distritoId:"San Antonio de Chuca", distritoName:"San Antonio de Chuca"},
        {distritoId:"Sibayo", distritoName:"Sibayo"},
        {distritoId:"Tapay", distritoName:"Tapay"},
        {distritoId:"Tisco", distritoName:"Tisco"},
        {distritoId:"Tuti", distritoName:"Tuti"},
        {distritoId:"Yanque", distritoName:"Yanque"},
    ],
    "Condesuyos":[
        {distritoId:"Andaray", distritoName:"Andaray"},
        {distritoId:"Cayarani", distritoName:"Cayarani"},
        {distritoId:"Chichas", distritoName:"Chichas"},
        {distritoId:"Chuquibamba", distritoName:"Chuquibamba"},
        {distritoId:"Iray", distritoName:"Iray"},
        {distritoId:"Rio Grande", distritoName:"Río Grande"},
        {distritoId:"Salamanca", distritoName:"Salamanca"},
        {distritoId:"Yanaquihua", distritoName:"Yanaquihua"}
    ],
    "Islay":[
        {distritoId:"Cocachacra", distritoName:"Cocachacra"},
        {distritoId:"Dean Valdivia", distritoName:"Deán Valdivia"},
        {distritoId:"Islay", distritoName:"Islay"},
        {distritoId:"Mejia", distritoName:"Mejía"},
        {distritoId:"Mollendo", distritoName:"Mollendo"},
        {distritoId:"Punta de Bombon", distritoName:"Punta de Bombón"}
    ],
    "La Union":[
        {distritoId:"Alca", distritoName:"Alca"},
        {distritoId:"Charcana", distritoName:"Charcana"},
        {distritoId:"Cotahuasi", distritoName:"Cotahuasi"},
        {distritoId:"Huaynacotas", distritoName:"Huaynacotas"},
        {distritoId:"Pampamarca", distritoName:"Pampamarca"},
        {distritoId:"Puyca", distritoName:"Puyca"},
        {distritoId:"Quechualla", distritoName:"Quechualla"},
        {distritoId:"Sayla", distritoName:"Sayla"},
        {distritoId:"Tauria", distritoName:"Tauría"},
        {distritoId:"Tomepampa", distritoName:"Tomepampa"},
        {distritoId:"Toro", distritoName:"Toro"}
    ]
};