export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

//Csv
export const CSV_HOUSES = 'CSV_HOUSES';
export const CSV_PARTICIPANTS_INMUNE = 'CSV_PARTICIPANTS_INMUNE';
export const CSV_HEALTH_POSTS = 'CSV_HEALTH_POSTS';
export const UPDATE_HOUSES = 'UPDATE_HOUSES';
export const CSV_CLEAN = 'CSV_CLEAN';

//Login
export const LOGIN_INTO = 'LOGIN_EXIT';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_END = 'LOGIN_END';

//Denuncia
export const GET_DENUNCIATIONS = 'GET_DENUNCIATIONS';
export const ADD_DENUNCIATION = 'ADD_DENUNCIATION';
export const UPDATE_DENUNCIATION = 'UPDATE_DENUNCIATION';

//Inspeccion
export const GET_INSPECTIONS = 'GET_INSPECTIONS';
export const ADD_INSPECTION = 'ADD_INSPECTION';

//Cimex
export const ADD_CIMEX = 'ADD_CIMEX';

//Snipper
export const CHANGE_SPINNER = 'CHANGE_SPINNER';