export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';

//Alertas
export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

//Csv
export const CSV_HOUSES = 'CSV_HOUSES';
export const CSV_PARTICIPANTS_INMUNE = 'CSV_PARTICIPANTS_INMUNE';
export const CSV_HEALTH_POSTS = 'CSV_HEALTH_POSTS';
export const UPDATE_HOUSES = 'UPDATE_HOUSES';
export const CSV_CLEAN = 'CSV_CLEAN';

//Login
export const LOGIN_INTO = 'LOGIN_EXIT';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_END = 'LOGIN_END';

//Denuncia
export const GET_DENUNCIATIONS = 'GET_DENUNCIATIONS';
export const ADD_DENUNCIATION = 'ADD_DENUNCIATION';
export const EDIT_DENUNCIATION = 'EDIT_DENUNCIATION';
export const UPDATE_DENUNCIATION = 'UPDATE_DENUNCIATION';
export const DISABLE_EDIT_DENUNCIATION = 'DISABLE_EDIT_DENUNCIATION';
export const BTN_ADD_DENUNCIATION = 'BTN_ADD_DENUNCIATION';
export const BTN_EDIT_DENUNCIATION = 'BTN_EDIT_DENUNCIATION';
export const CLEAN_BTN_DENUNCIATION = 'CLEAN_BTN_DENUNCIATION';

//Inspeccion
export const GET_INSPECTIONS = 'GET_INSPECTIONS';
export const ADD_INSPECTION = 'ADD_INSPECTION';
export const BTN_INSPECTION = 'BTN_INSPECTION';

//Cimex
export const ADD_CIMEX = 'ADD_CIMEX';

//Snipper
export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';

//Rociados
export const BTN_ROC = "BTN_ROC";
export const BTN_ADD_ROCIADO = "BTN_ADD_ROCIADO";
export const DISABLED_BTN_ADD_ROCIADO = "DISABLED_BTN_ADD_ROCIADO";
export const ADD_ROCIADO = "ADD_ROCIADO";
export const GET_ROCIADOS = "GET_ROCIADOS";
