export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

//Csv
export const READ_CSV = 'READ_CSV';
export const CSV_PARTICIPANTS_INMUNE = 'CSV_PARTICIPANTS_INMUNE';
export const CSV_HEALTH_POSTS = 'CSV_HEALTH_POSTS';

//Denuncia
export const GET_DENUNCIATIONS = 'GET_DENUNCIATIONS';
export const ADD_DENUNCIATION = 'ADD_DENUNCIATION';
export const UPDATE_DENUNCIATION = 'UPDATE_DENUNCIATION';

//Inspeccion
export const GET_INSPECTIONS = 'GET_INSPECTIONS';
export const ADD_INSPECTION = 'ADD_INSPECTION';

